name: Create OG Images

on: push

jobs:
  social-images:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create Base Images
        run: npm run social-images

      - name: Create Images
        run: npm run og-images

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Add new og social image."
